_wandb:
    value:
        cli_version: 0.23.0
        e:
            rl8lhld2lrt6u36r19hgctzle9dczqst:
                args:
                    - --config
                    - configs/examples/ae_synthetic.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3935709487104"
                        used: "112491659264"
                email: mwilcoxson@berkeley.edu
                executable: /home/mwil/miniconda3/envs/mae/bin/python
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-2ace1625-6fa3-0f1b-2c57-b2e6779c2e7f
                host: DefinePRO-224902-2
                memory:
                    total: "132525973504"
                os: Linux-6.14.6-061406-generic-x86_64-with-glibc2.39
                program: /home/mwil/mae_ae_test/main.py
                python: CPython 3.12.12
                root: /home/mwil/mae_ae_test
                startedAt: "2025-11-22T23:04:52.954788Z"
                writerId: rl8lhld2lrt6u36r19hgctzle9dczqst
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
checkpoint_dir:
    value: ./checkpoints/ae_gaussian
dataset:
    value:
        batch_size: 128
        dataset_name: gaussian_mixture
        input_dim: 64
        n_components: 8
        n_samples: 20000
        normalize: true
        random_state: 42
        train_split: 0.8
device:
    value: cuda
experiment_name:
    value: mlp_ae_gaussian_mixture
model:
    value:
        params:
            activation: relu
            dropout: 0.1
            hidden_dims:
                - 512
                - 256
                - 128
            latent_dim: 32
        type: mlp_ae
num_epochs:
    value: 100
objective:
    value:
        params:
            loss_type: mse
            reduction: mean
        type: reconstruction
optimizer:
    value:
        lr: 0.001
        type: adam
        weight_decay: 1e-5
seed:
    value: 42
wandb_project:
    value: autoencoder-training
